# https://samtools.github.io/hts-specs/SAMv1.pdf 

rule trim_short_reads:
    input:
        "short-reads.fq.gz"
    output:
        "trimmed-short-reads.fasta"
    script:
        "trim_by_tag_length.py short-reads.fq.gz 25 > trimmed-short-reads.fasta"

rule trim_long_reads:
    input:
        "long-reads.fq.gz"
    output:
        "trimmed-long-reads.fasta"
    script:
        "trim_by_tag_length.py long-reads.fq.gz 92 > trimmed-long-reads.fasta"

rule install_bwa:
    output:
        "bwa-mem2-2.0pre2_x64-linux/bwa-mem2"
    shell:
        "curl -L https://github.com/bwa-mem2/bwa-mem2/releases/download/v2.0pre2/bwa-mem2-2.0pre2_x64-linux.tar.bz2 | tar jxf -"

rule map_short_reads:
    input:
        "bwa-mem2-2.0pre2_x64-linux/bwa-mem2",
        "reference.fasta",
        "trimmed-short-reads.fasta"
    output:
        "mapping.sam"
    shell:
        """
        bwa-mem2-2.0pre2_x64-linux/bwa-mem2 index reference.fasta
        bwa-mem2-2.0pre2_x64-linux/bwa-mem2 mem reference.fasta work/trimmed-reads.fasta > mapping.sam
        """

rule map_short_reads:
    input:
        "reference.fasta",
        "trimmed-long-reads.fasta"
    output:
        "mapping.sam"
    conda:
        "minimap2.yml"
    shell:
        """
        minimap2 -x map-ont -d reference reference.fasta > /dev/null 2>&1
        minimap2 -c -a -o mapping.nonunique.sam -N 1 -x map-ont reference trimmed-long-reads.fasta
        samtools view -bq 1 mapping.nonunique.sam > mapping.sam
        """

rule convert_sam_to_bam:
    input:
        "mapping.sam"
    output:
        "mapping.bam",
        "unmapped.fa"
    conda:
        "samtools.yml"
    shell:
        """
        samtools view -S -b bwa.sam > bwa.bam
        samtools view -f 4 bwa.bam > unmapped.sam
        samtools view -S -b unmapped.sam > unmapped.bam
        samtools bam2fq unmapped.bam | seqtk seq -A - > unmapped.fa
        """

rule create_insertion_plot:
    input:
        "mapping.sam"
    output:
        "summary-stats.tsv"
    script:
        "sam_to_insert_plot.py mapping.sam reference.fasta"
